function prony_compare_fig(X1, YMatrix1, YMatrix2,om)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 26-Jun-2015 11:59:14

% Create figure
figure1 = figure('Renderer','painters');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.540942928039702 0.775 0.3718874430146],...
    'FontSize',12);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.00015 0.00025]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);

    for lp =1:size(YMatrix1,1)
        set(plot1(lp),'LineWidth',2,'DisplayName',strcat('\omega=',num2str(om(lp),3),'cm^{-1}'))
    end

% Create ylabel
ylabel('Signal, a.u.','FontSize',14);

% Create subplot
subplot1 = subplot(2,1,2,'Parent',figure1,'FontSize',12);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-6e-05 0.00013]);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot1);
set(plot2(1),'MarkerSize',2,'Marker','o','LineStyle','none',...
    'DisplayName','Actually signal');
set(plot2(2),'LineWidth',2,'Color',[1 0 0],'DisplayName','Full Prony');

% Create xlabel
xlabel('t_2(fs)','FontSize',14);

% Create ylabel
ylabel('Signal, a.u.','FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Orientation','horizontal',...
    'Position',[0.231196581196581 0.810587262200166 0.658974358974359 0.0794044665012407]);

% Create legend
legend(subplot1,'show');

